[package]
name = "harbor"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "3.0.17"
async-graphql-axum = "3.0.17"
axum = "0.4.2"
bollard = "0.11.1"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
