[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../entity" }

[dependencies.sea-schema]
version = "^0.7.0"
default-features = false
features = ["migration", "debug-print"]
